### ISSUE TITLE
Fastboot ROM flashing issue

### ISSUE THREAD

**Issue by arvind-gr** [geoanto555/android_device_xiaomi_lime#1]
Hi, I am raising an issue here as I have spent more than half day and not locating info. Xiaomi Eu forum is locked - https://forum.xda-developers.com/t/warning-about-xiaomi-eu.3837109/#post-84432479 

I have lime-india, variant similar to https://xiaomi.eu/community/threads/does-redmi-9t-share-its-rom-with-redmi-note-9-4g-china-version.59001

Tried using available TWRP and Have downloaded Stable MIUI v12 - xiaomi.eu_multi_HMNote94G_HM9T_V12.0.11.0.QJQCNXM_v12-10.zip
This file cannot be transferred to the phone to flash as TWRP gets FBE encrypted error

As mentioned here, https://xiaomi.eu/community/threads/does-redmi-9t-share-its-rom-with-redmi-note-9-4g-china-version.59001/#post-581957 I tried fastboot but,
Unzipping it gives system.new.dat.br, etc which cant be flashed via fastboot flash system. Gives FAILED (remote: 'Partition not found')

So I do not know how to flash it, Pls do help @geoanto555

**Comment by geoanto555** [comment]
Hi. can you boot to twrp?
What is the problem?
flash the twrp 
open terminal 
fastboot flash recovery nameofrecovery.img
fastboot reboot with vol + to boot
Wipe/format data -- > yes
reboot recovery
copy rom to internal or usb-otg or sdcard
flash the rom and again, format data

**Comment by arvind-gr** [comment]
Yes I was able to boot to TWRP
Formatted Data as well, but somehow even after recovery reboot it shows FBE decryption error still

copy rom to internal or usb-otg or sdcard --> This did the trick, I am now able to boot to ROM
After flashing ROM via OTG, I am able to mount /sdcard in recovery as well
Thanks!

**Comment by geoanto555** [comment]
Thanks for the testing..

**Comment by adligit2** [comment]
same ar..cannot flash rom in twrp cause FBE error..

**Comment by geoanto555** [comment]
"fbe" after format is not error.
What is the problem?
format data / reboot recovery and copy the rom to internal..
If mtp not working reboot recovery again.

**Comment by ukumar009** [comment]
facing same error @geoanto555 :-( 

I performed the following steps:
1. flash the twrp
2. open terminal
3. fastboot flash recovery nameofrecovery.img
4. fastboot reboot with vol + to boot
5. Wipe/format data -- > yes
6. reboot recovery
7. copy rom to internal or usb-otg or sdcard
8. flash the rom and again, format data

After that, I rebooted to recovery when I tried performing Reboot System. I am seeing the following:
"No OS Installed! Are you sure you wish to reboot?" 
Could you please help me @geoanto555 

Following are the observations:
after doing all the above steps at Step-8 still, I am seeing the same error:
"E:Unable to decrypt FBE device". but still, I am able to install CR Droid and I observed the installation of CRDroid to Done.

attaching logs
dmesg: https://ufile.io/hiqf116n
recovery: https://ufile.io/23jwt3ft

Thanks,
